[package]
name = "file-encryptor-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.82"
bincode = "1.3.3"
generic-array = "1.0.0"
pbkdf2 = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.8"
typenum = "1.17.0"
